name: Make Nightly

permissions:
  contents: write

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: 17
          cache: 'gradle'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew assemblePreview

      - name: Sign apk
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/apk/preview
          signingKeyBase64: ${{ secrets.SIGNING_KEYSTORE }}
          alias: ${{ secrets.SIGNING_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.SIGNING_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "35.0.0"

      - name: Copy build artifacts
        run: |
          set -e

          commit_count=$(git rev-list --count HEAD)
          echo "COMMIT_COUNT=$commit_count" >> $GITHUB_ENV

          declare -a apks=("universal" "arm64-v8a" "armeabi-v7a" "x86" "x86_64")

          printf "%s\n" "${apks[@]}" | xargs -n 1 -I {} sh -c '
          cp app/build/outputs/apk/preview/app-{}-preview-signed.apk mpvKt-{}.apk'

      - name: Upload the universal artifact
        uses: actions/upload-artifact@v4
        with:
          path: ./mpvKt-universal.apk
          name: universal-r${{ env.COMMIT_COUNT }}
      - name: Upload the arm64-v8a artifact
        uses: actions/upload-artifact@v4
        with:
          path: ./mpvKt-arm64-v8a.apk
          name: arm64-v8a-r${{ env.COMMIT_COUNT }}
      - name: Upload the armeabi-v7a artifact
        uses: actions/upload-artifact@v4
        with:
          path: ./mpvKt-armeabi-v7a.apk
          name: armeabi-v7a-r${{ env.COMMIT_COUNT }}
      - name: Upload the x86 artifact
        uses: actions/upload-artifact@v4
        with:
          path: ./mpvKt-x86.apk
          name: x86-r${{ env.COMMIT_COUNT }}
      - name: Upload the x86_64 artifact
        uses: actions/upload-artifact@v4
        with:
          path: ./mpvKt-x86_64.apk
          name: x86_64-r${{ env.COMMIT_COUNT }}
